version: '3'
services:
  php-environment:
    container_name: php-apache-rekenen
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
